name: ci
on:
  workflow_dispatch:
    inputs: 
      tf_resource_json:
        type: string
        description: 'tf input payload'
        required: true
        default: '{}'  
jobs:
  build:
    name: "Test WIF"
    runs-on: [ GKE ]
    timeout-minutes: 90
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          workload_identity_provider: 'projects/947838827407/locations/global/workloadIdentityPools/github-enterprise-pool/providers/github-oidc'
          service_account: 'test-sa-01@gcp-asadalim-test-01.iam.gserviceaccount.com'
          access_token_lifetime: '100s'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      - name: set crdential_file
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
      - name: Run gcloud
        run: gcloud projects list
